### ISSUE TITLE
Unexpected keyword argument 'dissimilairity_function'

### ISSUE THREAD

**Issue by Nilser3** [codingfisch/torchreg#1]
Hi @codingfisch 

I've been testing this nice approach to register with Torch in MRI data, and when I wanted to apply `"dice_loss"` metric , I got the message that:
`TypeError: __init__() got an unexpected keyword argument 'dissimilairity_function'`

but when looking at your code and README
https://github.com/codingfisch/torchreg/blob/e9c321e1218e4f1e1302759c4b5be219f245e555/torchreg/affine.py#L8C39-L8C39

I think there is a typing error in the README:,
`dissimilairity_function `  for  `dissimilarity_function`

Best,

Nilser

**Comment by Nilser3** [comment]
I think a similar issue for `zoom `and `with_zoom`  in "Custom initial parameters" from README

**Comment by codingfisch** [comment]
Well spotted!
